# Generated by Django 4.1 on 2022-08-22 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("info_park_v2", "0003_account_delete_myaccount"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="mail",),
        migrations.RemoveField(model_name="account", name="name",),
        migrations.RemoveField(model_name="account", name="password",),
        migrations.AddField(
            model_name="account",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
