# Generated by Django 4.1 on 2022-08-23 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("info_park_v2", "0004_remove_account_mail_remove_account_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="content",),
    ]
